[book]
title = "折腾技术 / PLAY TECH 🚀"
description = "分享一些有趣好玩的技术内容。"
authors = ["soulteary"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "runbook"

[output.html]
git-repository-url="https://github.com/soulteary/zheteng-tech"
edit-url-template="https://github.com/soulteary/zheteng-tech/edit/main/{path}"
google-analytics = "G-RXQS80RJYV"

[output.html.search]
enable = false
